// Code generated by "hcl2-schema -type VBoxVersionConfig /Users/azr/go/src/github.com/hashicorp/packer/builder/virtualbox/common/vbox_version_config.go"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
)

func (*VBoxVersionConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	return s
}
